version: '3.4'

services:
  rabbitmq:
    container_name: rabbitmq
    restart: always
    ports:
        - "5672:5672"
        - "15672:15672"

  catalog.api:
    container_name: catalog.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://catalogdb:27017"
    ports:
      # Acesso direto removido - Utilizar API atraves do OcelotApiGw
      # - "8000:80"
      - "80"
    depends_on:
      - catalogdb
    networks:
      - catalog-network
      - elastic-network

  basket.api:
    container_name: basket.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "CacheSettings:ConnectionString=basketdb:6379"
      - "GrpcSettings:DiscountUrl=http://discount.grpc"
      - "EventBusSettings:HostAddress=amqp://guest:guest@rabbitmq:5672"
    ports:
      # Acesso direto removido - Utilizar API atraves do OcelotApiGw
      - "80"	  
      # - "8001:80"

    depends_on:
      - basketdb
    networks:
      - basket-network
      - elastic-network

  discount.api:
    container_name: discount.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=Server=discountdb;Port=5432;Database=DiscountDb;User Id=admin;Password=admin1234;"
    ports:
    # Acesso direto removido - Utilizar API atraves do OcelotApiGw
    #  - "8002:80"
      - "80"	  
    depends_on:
      - discountdb
    networks:
      - discount-network
      - elastic-network

  discount.grpc:
    container_name: discount.grpc
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8003:80"
    depends_on:
      - discountdb
    networks:
      - basket-network
      - discount-network
      - elastic-network

  ordering.api:
    container_name: ordering.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:OrderingConnectionString=Server=orderdb;Database=OrderDb;User Id=sa;Password=SenhaBD965;Trust Server Certificate=true;"
      - "EventBusSettings:HostAddress=amqp://guest:guest@rabbitmq:5672"
    ports:
      # Acesso direto removido - Utilizar API atraves do OcelotApiGw
      # - "8004:80"
      - "80"
    depends_on:
      - orderdb
    networks:
      - ordering-network
      - elastic-network

  ocelotapigw:
    container_name: ocelotapigw
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8010:80"
    depends_on:
        - catalog.api
        - basket.api
        - discount.api
        - ordering.api
    networks:
      - catalog-network
      - basket-network
      - discount-network
      - ordering-network
      - frontend-network
      - elastic-network

  shopping.aggregator:
    container_name: shopping.agg
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ApiSettings:CatalogUrl=http://catalog.api"
      - "ApiSettings:BasketUrl=http://basket.api"
      - "ApiSettings:OrderingUrl=http://ordering.api"
    ports:
      - "8005:80"
    depends_on:
      - catalog.api
      - basket.api
      - ordering.api
    networks:
      - catalog-network
      - basket-network
      - discount-network
      - ordering-network
      - frontend-network
      - elastic-network

  aspnetrunbasics6:
    container_name: webfrontend
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ApiSettings:GatewayAddress=http://ocelotapigw"
      - "ElasticConfiguration:Uri=http://elasticsearch:9200"
    ports:
      - "8006:80"
    depends_on:
      - ocelotapigw
      - catalog.api
      - basket.api
      - discount.api
      - ordering.api
    networks:
      - frontend-network
      - elastic-network

  elasticsearch:
    container_name: elasticsearch
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - xpack.monitoring.enabled=true
      - xpack.watcher.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - elastic-network
  
  kibana:
    container_name: kibana
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601
    networks:
      - elastic-network

  webstatus:
    container_name: webstatus
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - HealthChecksUI__HealthChecks__0__Name=Catalog Health Check
      - HealthChecksUI__HealthChecks__0__Uri=http://catalog.api/hc
      - HealthChecksUI__HealthChecks__1__Name=Basket Health Check
      - HealthChecksUI__HealthChecks__1__Uri=http://basket.api/hc
      - HealthChecksUI__HealthChecks__2__Name=Discount Health Check
      - HealthChecksUI__HealthChecks__2__Uri=http://discount.api/hc
      - HealthChecksUI__HealthChecks__3__Name=Ordering Health Check
      - HealthChecksUI__HealthChecks__3__Uri=http://ordering.api/hc
      - HealthChecksUI__HealthChecks__4__Name=Shopping Aggregator Health Check
      - HealthChecksUI__HealthChecks__4__Uri=http://shopping.agg/hc
      - HealthChecksUI__HealthChecks__5__Name=AspnetRunBasics WebMVC Health Check
      - HealthChecksUI__HealthChecks__5__Uri=http://webfrontend/hc
    ports:
      - 8007:80
    networks:
      - frontend-network
      - catalog-network
      - basket-network
      - discount-network
      - ordering-network