version: '3.4'

services:
  rabbitmq:
    container_name: rabbitmq
    restart: always
    ports:
        - "5672:5672"
        - "15672:15672"

  ocelotapigw:
    container_name: ocelotapigw
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8010:80"
    depends_on:
        - catalog.api
        - basket.api
        - discount.api
        - ordering.api

