version: '3.4'

services:
  rabbitmq:
    container_name: rabbitmq
    restart: always
    ports:
        - "5672:5672"
        - "15672:15672"

  ocelotapigw:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5010:80"

